'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, CheckCircle2, Clock, MessageSquarePlus, Pencil, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Avatar } from '@/components/ui/avatar'
import { privateAvatarUrl } from '@/lib/avatar-url'
import { ContentBody } from '@/components/app/content-body'
import { cn } from '@/lib/utils'
import { decideApproval } from '@/app/actions/editorial'

type Voter = { userId:string; decision:string; comment?:string; decidedAt?:string; name:string; initials:string; color?:string; role:string }
type Approval = { id:string; status:string; title:string; type:string; pauta:string; date:string; voters:Voter[]; currentUserId:string; contentId?:string; isRequester?:boolean }
type Content = { title?:string; subtitle?:string; body?:string; version?:string }

export function ReviewView({ approval, content, requester }: { approval: Approval; content?: Content; requester?: { name:string; initials:string; color?:string; avatarPath?:string|null; role:string } }) {
  const [decision,setDecision] = useState<'approved'|'changes_requested'|null>(null)
  const [note,setNote] = useState('')
  const approved = approval.voters.filter(v=>v.decision==='approved')
  const pending = approval.voters.filter(v=>v.decision==='pending')
  const rejected = approval.voters.filter(v=>v.decision==='changes_requested')
  const currentVoter = approval.voters.find(v=>v.userId===approval.currentUserId)
  const canVote = approval.status==='pending' && currentVoter?.decision==='pending'

  return <div><nav className="mb-4 flex items-center gap-1 text-xs text-muted-foreground"><Link href="/aprovacoes" className="flex items-center gap-1 hover:text-foreground"><ArrowLeft className="size-3.5" />Aprovações</Link><span>/</span><span className="text-foreground">{approval.title}</span></nav>
    {approval.status === 'approved' && <Card className="mb-4 flex items-center gap-3 border-success/30 bg-success/10 p-4"><CheckCircle2 className="size-6 shrink-0 text-success" /><div><p className="text-sm font-semibold text-success">Aprovado por todos — pronto para ser publicado.</p><p className="text-xs text-muted-foreground">Todas as pessoas responsáveis já decidiram. Nenhuma ação a mais é necessária aqui.</p></div></Card>}
    <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-border px-6 py-3"><span className="text-xs text-muted-foreground">{approval.type}</span><span className="flex items-center gap-2">{approval.status === 'approved' && <span className="inline-flex items-center gap-1 rounded-full bg-success/15 px-2 py-0.5 text-xs font-medium text-success"><Check className="size-3" />Aprovado</span>}<span className="text-xs text-muted-foreground">{content?.version}</span>{approval.status === 'pending' && approval.isRequester && approval.contentId && <Link href={`/conteudos/${approval.contentId}`} className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-1 text-xs font-medium hover:bg-muted"><Pencil className="size-3" />Editar matéria</Link>}</span></div><article className="px-6 py-8 lg:px-10"><p className="text-xs font-medium uppercase tracking-wide text-primary">{approval.pauta}</p><h1 className="mt-2 font-serif text-3xl font-bold leading-tight text-balance">{content?.title || approval.title}</h1>{content?.subtitle && <p className="mt-3 text-lg text-muted-foreground">{content.subtitle}</p>}<div className="mt-6 flex flex-col gap-4 text-base leading-relaxed"><ContentBody body={content?.body} /></div></article></Card>
      <aside className="flex flex-col gap-4"><Card className="p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Progresso da aprovação</h2><span className="text-sm font-semibold">{approved.length}/{approval.voters.length}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-success transition-all" style={{width:`${approval.voters.length ? approved.length/approval.voters.length*100 : 0}%`}} /></div>{rejected.length>0 && <p className="mt-3 text-xs font-medium text-destructive">Ajustes solicitados por {rejected[0].name}</p>}</Card>
        <Card className="p-5"><h2 className="text-sm font-semibold">Já aprovaram</h2><VoterList voters={approved} empty="Nenhuma aprovação registrada ainda." approved />{rejected.length > 0 && <><h2 className="mt-5 text-sm font-semibold">Solicitaram ajustes</h2><VoterList voters={rejected} empty="Nenhum ajuste solicitado." rejected /></>}<h2 className="mt-5 text-sm font-semibold">Ainda falta</h2><VoterList voters={pending} empty="Todas as pessoas já decidiram." /></Card>
        <Card className="p-5"><div className="flex items-center gap-2"><Avatar initials={requester?.initials || '?'} color={requester?.color} src={privateAvatarUrl(requester?.avatarPath)} size="sm" /><div><p className="text-sm font-medium">{requester?.name}</p><p className="text-xs text-muted-foreground">Solicitou em {approval.date}</p></div></div></Card>
        <Card className="p-5"><form action={decideApproval}><input type="hidden" name="id" value={approval.id}/><input type="hidden" name="decision" value={decision || ''}/><h2 className="text-sm font-semibold">Sua decisão</h2>{!canVote && <p className="mt-2 text-sm text-muted-foreground">{approval.status!=='pending' ? 'Esta rodada já foi encerrada.' : currentVoter?.decision==='approved' ? `Você aprovou${currentVoter.decidedAt ? ` em ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(currentVoter.decidedAt))}` : ''}. Agora aguardamos as outras pessoas.` : currentVoter?.decision==='changes_requested' ? 'Você já solicitou ajustes nesta rodada.' : 'Você acompanha esta rodada, mas não está entre os votantes.'}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><DecisionButton active={decision==='approved'} disabled={!canVote} onClick={()=>setDecision('approved')} icon={Check} label="Aprovar" /><DecisionButton active={decision==='changes_requested'} destructive disabled={!canVote} onClick={()=>setDecision('changes_requested')} icon={X} label="Pedir ajustes" /></div><label className="mt-4 flex items-center gap-1.5 text-xs font-medium text-muted-foreground"><MessageSquarePlus className="size-3.5"/>Comentário</label><textarea name="note" value={note} onChange={e=>setNote(e.target.value)} disabled={!canVote} rows={3} className="mt-1.5 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm disabled:opacity-60" placeholder="Registre uma observação"/><Button type="submit" className="mt-4 h-11 w-full" disabled={!canVote || !decision || (decision==='changes_requested'&&!note.trim())}>Confirmar decisão</Button></form></Card>
      </aside></div></div>
}

function VoterList({ voters, empty, approved=false, rejected=false }: { voters:Voter[]; empty:string; approved?:boolean; rejected?:boolean }) { return <div className="mt-3 flex flex-col gap-3">{voters.length ? voters.map(v=><div key={v.userId} className="flex items-start gap-2"><span className={cn('mt-0.5 flex size-6 items-center justify-center rounded-full',approved?'bg-success/15 text-success':rejected?'bg-destructive/10 text-destructive':'bg-warning/15 text-warning-foreground')}>{approved?<Check className="size-3.5"/>:rejected?<X className="size-3.5"/>:<Clock className="size-3.5"/>}</span><div><p className="text-sm font-medium">{v.name}</p><p className="text-xs text-muted-foreground">{v.role}{v.decidedAt?` · ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v.decidedAt))}`:''}</p>{v.comment&&<p className="mt-1 text-xs leading-relaxed">{v.comment}</p>}</div></div>) : <p className="text-xs text-muted-foreground">{empty}</p>}</div> }

function DecisionButton({active,disabled,onClick,icon:Icon,label,destructive=false}:{active:boolean;disabled:boolean;onClick:()=>void;icon:typeof Check;label:string;destructive?:boolean}) { return <button type="button" disabled={disabled} onClick={onClick} className={cn('flex items-center justify-center gap-1 rounded-lg border px-2 py-2 text-sm font-medium disabled:opacity-50',active?(destructive?'border-destructive bg-destructive/10 text-destructive':'border-success bg-success/10 text-success'):'border-border text-muted-foreground')}><Icon className="size-4"/>{label}</button> }
